### ISSUE TITLE
Performance for Virtual Screen

### ISSUE THREAD

**Issue by ghost** [mkernel/EWProxyFramebuffer#4] opened 2014-10-18 17:37 UTC
When I run the second virtual display, there is considerable lag on my MBP Retina. Is there any way to reduce this or any obvious reason this is happening?

Occurs on every resolution.

**Comment by andreacremaschi** [comment] 2014-10-19 22:50
This is a duplicate of https://github.com/andreacremaschi/Syphon-virtual-screen/issues/17

**Comment by OskarGroth** [comment] 2015-06-28 22:19
There is a solution indicated here: http://stackoverflow.com/questions/26502110/simulate-screen

**Closed as completed** 2015-06-28 23:19 UTC
